title: "www.ironfroggy.com"
subtitle: "A web place for Calvin Spealman"
packs:
- "jules:html5boilerplate"
- "jules:lesscss"
- "jules:atom"
- "jules:pygments"
- "jules:foundation-icons-general-enclosed"
- "jules:foundation-icons-general"
- "dir:templates"
- "dir:static"
- "dir:contents"
google_analytics_id: "UA-953592-18"
domain: "www.ironfroggy.com"
default_author: "Calvin Spealman <ironfroggy@gmail.com>"
tag_path: "tags/{tag}/"
disqus:
    enabled_default: true
ignore:
- "*.swp"
- "*.swo"
- "~*"
bundle_defaults:
    output_ext: ""
collections:
    tags:
        match:
            status: published
        group_by:
            in: tags
        meta:
            render: jinja2
            template: tag.j2
    series:
        group_by:
            is: series
        order: publish_time
        meta:
            render: jinja2
            template: series.j2
