title: "www.ironfroggy.com"
subtitle: "A web place for Calvin Spealman"
plugins:
- "mysiteplugins"
packs:
- "jules:html5boilerplate"
- "jules:lesscss"
- "jules:atom"
- "jules:pygments"
- "jules:foundation-icons-general-enclosed"
- "jules:foundation-icons-general"
- "dir:templates"
- "dir:static"
- "dir:contents"
google_analytics_id: "UA-953592-18"
domain: "www.ironfroggy.com"
default_author: "Calvin Spealman <ironfroggy@gmail.com>"
disqus:
    enabled_default: true
ignore:
- "*.swp"
- "*.swo"
- "~*"
bundle_defaults:
    output_ext: "html"
    render: jinja2
collections:
    year:
        group_by:
            is: year
        meta:
            render: jinja2
            template: archive.j2
            output_ext: ""
    month:
        group_by:
            is: month
        meta:
            render: jinja2
            template: archive.j2
            output_ext: ""
    tags:
        match:
            status: published
        group_by:
            in: tags
        meta:
            render: jinja2
            template: tag.j2
    series:
        group_by:
            is: series
        order: publish_time
        meta:
            render: jinja2
            template: series.j2
    topic:
        match:
            status: published
        group_by:
            is: topic
        meta:
            render: jinja2
            template: topic.j2
feed_campaign:
    name: "Feed Subscribers"
