title: "www.ironfroggy.com"
subtitle: "A web place for Calvin Spealman"
packs:
- "jules:html5boilerplate"
- "jules:lesscss"
- "jules:atom"
- "jules:pygments"
- "jules:foundation-icons-general-enclosed"
- "jules:foundation-icons-general"
- "dir:templates"
- "dir:static"
- "dir:contents"
google_analytics_id: "UA-953592-18"
domain: "www.ironfroggy.com"
default_author: "Calvin Spealman <ironfroggy@gmail.com>"
tag_path: "tags/{tag}/"
disqus:
    enabled_default: true
